### PR TITLE
add support for interface libraries

### PR DESCRIPTION
**Pull request by Green-Sky**

### CODE REVIEW

**Comment by alexreinking** [comment]
Thank you for the PR! I agree there is a gap in support for interface libraries that needs to be filled. 

I'm just a bit confused about the `SOURCES` property on `INTERFACE` libraries... shouldn't they always use `INTERFACE_SOURCES`?

**Comment by Green-Sky** [comment]
Did some reading in the manual and the code as is already sets the sources as `INTERFACE_SOURCES`.

> The [target_sources()](https://cmake.org/cmake/help/latest/command/target_sources.html#command:target_sources) command populates this property with values given to the PUBLIC and INTERFACE keywords.

**Comment by Green-Sky** [comment]
@alexreinking was there anything else?

**Comment by alexreinking** [comment]
@Green-Sky - thanks! I just merged with the latest master. Should be good to go if GCC 14 likes it.

**Pull request merged**
