### PR TITLE
Fix MSVC CI

### LINKED ISSUE #68: [BUG] CI complain about missing standard module interface for Windows build
Some tests are failing due to the following error:
```
cpp2util.h(48): fatal error C1011: cannot locate standard module interface. Did you install the library part of the C++ modules feature in VS setup?
```

### PR DESCRIPTION
**Pull request by alexreinking**
Fixes #68

### CODE REVIEW

**Comment by JohelEGP** [comment]
How about disabling <https://github.com/modern-cmake/cppfront/blob/main/regression-tests/cmake/CMakeLists.txt.in#L14>?
Then `__cpp_modules` won't be defined.
It'll do the same as Clang and GCC, "fake it till you make it".

**Comment by JohelEGP** [comment]
It's passing now: <https://github.com/modern-cmake/cppfront/actions/runs/5213070658>.

**Comment by alexreinking** [comment]
> How about disabling https://github.com/modern-cmake/cppfront/blob/main/regression-tests/cmake/CMakeLists.txt.in#L14? Then `__cpp_modules` won't be defined. It'll do the same as Clang and GCC, "fake it till you make it".

No, didn't work. Still get
```
C1011: cannot locate standard module interface. Did you install the library part of the C++ modules feature in VS setup?
```

**Comment by JohelEGP** [comment]
`__cpp_modules` is still defined: <https://compiler-explorer.com/z/naqe3exsY>.

**Comment by JohelEGP** [comment]
26fac8d broke the build another way.

**Pull request closed without merging**
